### ISSUE TITLE
How to acquire the wireframs annotations (i.e. junctions and lines) from existing annotations ? 

### ISSUE THREAD

**Issue by ToddBear** [zhou13/holicity#11]

**Comment by zhou13** [comment]
Sorry for missing your issues.

You basically have 2 options: The first one is using the OpenGL-based algorithm from my shapeunity repo:  https://drive.google.com/drive/folders/1ZviOGlkqi3q6QS_gnmxvo5ocMQ4JX7n2?usp=sharing. It should work out of box and is relatively robust. However, due to the precision of OpenGL z-buffer, it might miss some lines.

The ideal solution is to use some geometry processing algorithms to extract wireframes. You could start from our initial effort https://github.com/hjwdzh/VectorGraphRenderer. Unfortunately, the processing algorithm is very complex and I think that tool still contains some bugs.

**Comment by zhou13** [comment]
Let me know if you have other questions.

**Comment by ToddBear** [comment]
Sorry for the late feedback. 
Unfortunately, I'm not working on the relevant project anymore, so I did not try the above methods. 
Thank you for your kind offer of help.
